Gurobi inclusion
reworkhow/LPChoose.jl pull request #8
Opened 2020-09-01 18:25 UTC by liangend

2020-09-04 22:06 UTC, reworkhow requested changes

2020-09-04 22:06 UTC, reworkhow commented on LPChoose.jl
> +    using Gurobi
```
try
    @eval import Gurobi
    println("Gurobi has been installed.")
catch
    println("Gurobi is not installed. GLPK has been installed.")
end
```

2020-09-04 22:06 UTC, reworkhow commented on LPChoose.jl
> +    * ind_hap_lim is the maximum number of indentical haplotypes shared by selected individuals in each step for application 2, default value equal to 2.
identical

2020-09-04 22:06 UTC, reworkhow commented on LPChoose.jl
> +        else
make "30" an argument for the function as "time_limit".

2020-09-04 22:22 UTC, reworkhow commented on LPChoose.jl
> +    using Gurobi
consider a better printout here to give users some suggestion which solver to use.

2020-09-04 22:40 UTC, liangend commented
Updated Gurobi inclusion

2020-09-04 22:42 UTC, liangend reviewed
Updated Gurobi inclusion

2020-09-04 22:50 UTC, liangend reviewed
print out information

2020-09-05 03:47 UTC, reworkhow approved these changes

2020-09-05 03:47 UTC, reworkhow commented on LPChoose.jl
> +import_Gurobi = false  # import Gurobi package when import_Gurobi = true
We don't need import_Gurobi. I don't see you provide an interface for users for import_Gurobi. If it is available, we just load it.

2020-09-05 03:48 UTC, merged